### ISSUE TITLE
Upgrade to v1.4.4 from v1.4.3 not working with browserify v8.1.3

### ISSUE THREAD

**Issue by baseten** [joeybaker/remapify#32]
Since upgrading to v1.4.4 my builds have stopped working and I'm getting the `Cannot find module` error. Logging the `expandedAliases` in the `remapify:files` event shows the aliases seem to be built correctly so something else is going on. It looks like an additional path is being prepended to the src path for some reason. I'll try and debug and provide a bit more info later.

**Comment by akofman** [comment]
Same here.

**Comment by arthurmuchir** [comment]
+1

**Comment by noppanit** [comment]
+1

**Comment by mrChex** [comment]
+1

**Comment by jivinivan** [comment]
:+1:

**Comment by brandoshmando** [comment]
:+1:

**Comment by gpszymczak** [comment]
:+1:

**Comment by tplorts** [comment]
:+1:

**Comment by mkuchen** [comment]
:+1:

**Comment by Chochek** [comment]
:+1:

**Comment by joeybaker** [comment]
Hey folks — sorry for not responding earlier. This is actually a dupe of #24
